name: healthcare_mania_free
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+33

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^6.0.0

  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  path_provider: ^2.0.11
  intl: ^0.20.2
  fl_chart: ^1.1.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
